services:
  mongo:
    image: mongo:latest
    ports:
      - "17017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password

  postgres:
    image: postgres:latest
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lampjs